### PR TITLE
feat(k8s): allow showing links for job status

### PR DESCRIPTION
**Pull request by Charles546**
#### Description

To ease the pain of troubleshooting k8s jobs, this PR adds the feature of returning a few links for showing in various UI components.

### CODE REVIEW

**Comment by Charles546** [comment]
> One way, if we can do it safely, is to do a very generic thing here, with some limited string formatting, and then allow passing a log URL and a printf style pattern along that could be defined at the “system” or workflow level.

It IS implemented in a generic way.  The k8s driver calls whatever provider driver's (`gcloud-gke` in our case)`getJobLinks` method. If provider doesn't support it, just return a blank map. 

The actual logic for displaying the links are in this PR honeydipper/honeydipper-config-essentials#77 . It should look like below.

Screen Shot 2020-05-20 at 6 15 59 PM

**Comment by wyardley** [comment]
I guess I still think not baking the link into the driver is more flexible, as the link pattern may change or vary depending on various things (for example, the log path changed recently for newer GKE versions)

**Comment by Charles546** [comment]
The down side of putting the URL in the driver is that, we will need code changes when the URLs need to be changed.  But I can't find a cleaner way to do it on system level as of now.

**Comment by wyardley** [comment]
What if people aren’t using Stackdriver or are using a SAAS log provider like Sumologic or Loggly?

**Comment by Charles546** [comment]
Currently, we can't use `params` and `sysData` in function export, that's why we can't put the link templates in the `sysData` or `params`.  I am fixing that, so this is not needed any more.

**Pull request closed without merging**
