### PR TITLE
chore: clean up unused charts definition

### PR DESCRIPTION
**Pull request by Charles546**
#### Description
The charts are now managed in [honeydipper-charts](https://github.com/honeydipper/honeydipper-charts) repo.

### CODE REVIEW

**Comment by wyardley** [comment]
Can we move it the other direction instead?

**Comment by Charles546** [comment]
> Can we move it the other direction instead?

I want the chart version and app version to be disassociated. So, the app binary and the deployment template(chart) should go through different CI piplines and released with different cadence. I am not sure if coupling them into one single repo is the right approach. 

The `.Chart.AppVersion` acts as a default but doesn't limit the usage of the chart with other version of the app binary. This makes it prone to error with outdated default version.  One option is not using `.Chart.AppVersion` at all(removing it from the `Chart.yaml`). So, the `.Values.image.tag` becomes required. And, we don't have to keep updating the `AppVersion` in the chart. 

The whole helm community seems undecided how to handle this either.
https://github.com/helm/helm/issues/8194

**Review by wyardley — APPROVED** [review]

**Comment by wyardley** [comment]
Looks good. Makes sense about keeping it in the same pipeline, as long as we integrate ct etc., I think also good to have the artifact get pushed to the git release if we can, vs. committed to git.

Re-running the flaky test

**Pull request merged**
